name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: simple_bank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Test
      run: |
        make gotest
        # Trong make gotest, bạn cần thiết lập các biến môi trường để ứng dụng của bạn có thể kết nối với PostgreSQL
        export PGHOST=localhost
        export PGPORT=5432
        export PGDATABASE=mydatabase
        export PGUSER=myuser
        export PGPASSWORD=mypassword
        # Chạy các lệnh test ở đây
